// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace CrimeAlert.Web.Controllers {
    public partial class ApiController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ApiController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult UpdateReport() {
            return new T4MVC_JsonResult(Area, Name, ActionNames.UpdateReport);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult DeleteReport() {
            return new T4MVC_JsonResult(Area, Name, ActionNames.DeleteReport);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ApiController Actions { get { return MVC.Api; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Api";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Api";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string UpdateReport = "UpdateReport";
            public readonly string DeleteReport = "DeleteReport";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string UpdateReport = "UpdateReport";
            public const string DeleteReport = "DeleteReport";
        }


        static readonly ActionParamsClass_UpdateReport s_params_UpdateReport = new ActionParamsClass_UpdateReport();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpdateReport UpdateReportParams { get { return s_params_UpdateReport; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpdateReport {
            public readonly string reportId = "reportId";
            public readonly string securityToken = "securityToken";
            public readonly string isPublic = "isPublic";
            public readonly string comment = "comment";
            public readonly string locationLongtitude = "locationLongtitude";
            public readonly string locationLatitude = "locationLatitude";
        }
        static readonly ActionParamsClass_DeleteReport s_params_DeleteReport = new ActionParamsClass_DeleteReport();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteReport DeleteReportParams { get { return s_params_DeleteReport; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteReport {
            public readonly string reportId = "reportId";
            public readonly string securityToken = "securityToken";
        }
        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_ApiController: CrimeAlert.Web.Controllers.ApiController {
        public T4MVC_ApiController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.JsonResult UpdateReport(int reportId, string securityToken, bool isPublic, string comment, string locationLongtitude, string locationLatitude) {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.UpdateReport);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "reportId", reportId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "securityToken", securityToken);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "isPublic", isPublic);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "comment", comment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "locationLongtitude", locationLongtitude);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "locationLatitude", locationLatitude);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult DeleteReport(int reportId, string securityToken) {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.DeleteReport);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "reportId", reportId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "securityToken", securityToken);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
